# Site settings
title: Coding
header-img: "img/autumn2.jpg"
tagline: ""  
description: ""  
baseurl: ""
url: "http://wujunzero.github.io"  

# About/contact
owner: 
  name: "WuJun"
  email: wujunzero@163.com
  bio: ""

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: wujunzero
twitter_username: 
github_username: wujunzero  
facebook_username: wujunzero  
weibo_username: wujunzero  
zhihu_username: wujunzero

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Harbin

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "WuJun"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : wujunzero
  disqus :
      short_name : wujunzero

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation